#!/usr/bin/env bash
sudo apt update && sudo apt full-upgrade -y && \
sudo flatpak update -y && \
sudo fwupdmgr refresh --force && \
sudo fwupdmgr update -y && \
sudo apt autoremove -y && \
sudo apt autoclean -y && \
sudo apt clean && \
sudo flatpak uninstall --unused -y && \
rm -rf ~/.cache/thumbnails/* && \
sudo journalctl --vacuum-time=3d && \
sudo fwupdtool get-history | head -n 15 && \
sudo sed -i 's/#SystemMaxUse=/SystemMaxUse=50M/' /etc/systemd/journald.conf && sudo systemctl restart systemd-journald && \
sudo rm -rf /var/lib/systemd/coredump/* && \
echo "✨ System Update, Cleanup, and Cache Refresh Complete!"