#!/usr/bin/env bash
sudo dnf upgrade --refresh -y && \
sudo flatpak update && \
sudo fwupdmgr refresh --force && \
sudo fwupdmgr update && \
sudo dnf update  && \
sudo dnf autoremove && \
sudo flatpak uninstall --unused && \
sudo dnf clean all && \
sudo rm -rf ~/.cache/thumbnails/* && \
sudo journalctl --vacuum-time=3d && \
sudo rm -rf /var/cache/dnf/* && \
sudo dnf makecache && \
sudo dnf check-update && \
sudo du -sh /var/cache/dnf && \
sudo fwupdtool get-history | head -n 15 && \
sudo sed -i 's/#SystemMaxUse=/SystemMaxUse=50M/' /etc/systemd/journald.conf && sudo systemctl restart systemd-journald && \
sudo rm -rf /var/spool/abrt/* && \
sudo rm -rf /var/lib/systemd/coredump/* && \
echo "✨ System Update, Cleanup, and Cache Refresh Complete!"
